# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-maggu2810-ct
KERNEL_VERSION=3.4.103-2

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  echo "MAGGU2810: arg1: ${1}; arg2: ${2}"
  depmod ${KERNEL_VERSION}
}

post_upgrade() {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  echo "MAGGU2810: arg1: ${1}; arg2: ${2}"
  depmod ${KERNEL_VERSION}
}
